fundation/config/routes.rb
Rails.application.routes.draw do
  resources :compras
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'compras#index'
end

fundation/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fundation/app/models/compra.rb
class Compra < ApplicationRecord
end

fundation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

fundation/app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra fue creada.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra fue actualizada.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra fue eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:FechaCompra, :Monto, :Cliente)
    end
end

fundation/app/helpers/application_helper.rb
module ApplicationHelper
end

fundation/app/helpers/compras_helper.rb
module ComprasHelper
end

fundation/app/views/compras/_form.html.erb
<%= form_for(compra) do |f| %>
  <% if compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Fecha_Compra %>
    <%= f.date_select :FechaCompra %>
  </div>

  <div class="field">
    <%= f.label :Monto %>
    <%= f.text_field :Monto %>
  </div>

  <div class="field">
    <%= f.label :Cliente %>
    <%= f.text_field :Cliente %>
  </div>

  <div class="actions">
    <%= f.submit class:'button radius success' %>
  </div>
<% end %>

fundation/app/views/compras/edit.html.erb
<h1>Editar Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Mostrar', @compra, class:'button radius warning' %> |
<%= link_to 'Atras', compras_path, class:'button radius secondary'%>

fundation/app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compras</h1>

<table>
  <thead>
    <tr>
      <th>Fecha compra</th>
      <th>Monto</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.FechaCompra %></td>
        <td><%= compra.Monto %></td>
        <td><%= compra.Cliente %></td>
        <td><%= link_to 'Mostrar', compra, class:'button radius' %></td>
        <td><%= link_to 'Editar', edit_compra_path(compra), class:'button radius success' %></td>
        <td><%= link_to 'Eliminar', compra, method: :delete, data: { confirm: '¿Està seguro?' }, class:'button radius alert' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Compra', new_compra_path, class:'button radius success' %>

fundation/app/views/compras/new.html.erb
<h1>Nueva Compra</h1>

<%= render 'form', compra: @compra , button_name: 'Nueva Compra`'%>

<%= link_to 'Atras', compras_path, class:'button radius secondary' %>

fundation/app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha compra:</strong>
  <%= @compra.FechaCompra %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @compra.Monto %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @compra.Cliente %>
</p>

<%= link_to 'Editar', edit_compra_path(@compra),class:'button radius success'%> |
<%= link_to 'Atras', compras_path, class:'button radius secondary' %>

fundation/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>